### ISSUE TITLE
NBA League Pass Stutters or Crashes

### ISSUE THREAD

**Issue by jwwiii1982** [maxgalbu/xbmc.plugin.video.nba#1]
The stream starts fine, but maybe 5-10 minutes into it the stream starts to stutters or crashes back to the menu. Also, I tried changing the video quality from 720p to 540p and it never changes on the stream, but it does change in the settings.

**Comment by sobehouse** [comment]
Hi guys, I'm having issues with my nba league pass on kodi
with vs 8.0 kodi would crash as soon i click the Haddon
after i update with the 8.1 it crash right after i enter the second page of the addon,
please help thank

**Comment by maxgalbu** [comment]
8.1? The current version is 0.8.0, are you sure you're using this plugin?

> after i update with the 8.1 it crash right after i enter the second page of the addon,
which item of the list did you click? live, archive..? which second page?
