### ISSUE TITLE
2019-20 games not appearing

### ISSUE THREAD

**Issue by sosh45** [maxgalbu/xbmc.plugin.video.nba#101]
Hi
Have loved using this add-on over the past couple of years, however it doesn't seem to be showing a folder for the 2019-20 season (in the Archive section). There are also no games in the "This week" or "Last week" folders. 
Thanks

**Comment by ivankokan** [comment]
Without any additional information including a debug log from Kodi, no one is able to help.

Please go through issues #97, #98 and #99, check whether you experience the same and whether suggested solutions help you.

**Comment by sosh45** [comment]
All good now, seemed to be an issue with the version on the repository. The zipped version from github is working fine. Thanks :)
