### ISSUE TITLE
what is this call for?

### ISSUE THREAD

**Issue by chovy** [maxgalbu/xbmc.plugin.video.nba#11]
https://mf.svc.nhl.com/ws/media/mf/v2.3/key/silk/mediaid/40699103/kid/20106583

I see it returns binary data and I don't see what its being used for.

**Comment by maxgalbu** [comment]
Uhm, where is it called? nhl.com doesn't seem like the usual nba.com domain :)

**Comment by chovy** [comment]
haha. woops. wrong repo
