### ISSUE TITLE
NBA TV Live stops after ten minutes

### ISSUE THREAD

**Issue by nilbarc** [maxgalbu/xbmc.plugin.video.nba#12]
NBA TV Live streams seems to just stop after approximately ten minutes. There's no issues with bandwidth and it works fine as soon as it's restarted.

**Comment by maxgalbu** [comment]
Thanks for reporting the issue, I just need to buy a month of nba tv live to test it :)

**Comment by nilbarc** [comment]
I'll PayPal you the money if you want.

**Comment by maxgalbu** [comment]
Closing in favor of #16
