### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by PiQuer** [maxgalbu/xbmc.plugin.video.nba#14]
As of today I get an 404 error message whenever I enter live games or the archives.

**Comment by maxgalbu** [comment]
Thanks, I've released a new version, should update shortly

**Comment by nzeppos** [comment]
Had the same issue with v0.81, past weeks seem to be working OK, the issue occurs only with the current week (either selecting "this week" or any specific date after May 29th, eg. 2016-05-30).

I take it that something's wrong with the logic of these lines when the month changes?

file: - /storage/.kodi/addons/plugin.video.nba/games.py (line 129)
`        for day_of_week in range(7):
            scoreboard = 'http://data.nba.com/jsonp/5s/json/cms/noseason/scoreboard/%04d%02d%02d/games.json?callback=ciao' % \
                (date.year, date.month, date.day+day_of_week            scoreboard_request = urllib2.Request(scoreboard, None);
            scoreboard_response = str(urllib2.urlopen(scoreboard_request).read())
            scoreboard_response = scoreboard_response[scoreboard_response.find("{"):scoreboard_response.rfind("}")+1]
                              
            key = "%04d-%02d-%02d" % (date.year, date.month, date.day+day_of_week)
            scoreboards_jsons[key] = json.loads(scoreboard_response)`

As a quick workaround I simply used a hardcoded date of 20160530 and it worked fine. I take it that maxgalbu has provided a permanent solution so I'll download that newest version asap. Thanks a lot for the prompt response!! This plugin is the ultimate add-on for NBA League Pass!

**Comment by maxgalbu** [comment]
yep that was it :)
