### ISSUE TITLE
Cannot login anymore, cannot access any games or NBA TV

### ISSUE THREAD

**Issue by chovy** [maxgalbu/xbmc.plugin.video.nba#17]
https://paste.ubuntu.com/23201010/

It worked a week ago. I have international league pass...and I can watch fine on the web site.

I'm getting this back from browser in the xml which used to show the manifest url:

```
adaptive://nlds16.neulion.com:443/nlds/nba/nba247/as/live/s_nba247_live_game_hd?plid=xxxx&auth_key=xxx-1474252150-32-*&nltid=nba&nltdt=0&uid=xxxx
```

also publish endpoint is now: https://watch.nba.com/service

edit: nevermind, had to query with iPad user agent. but the endpoint still changed.

**Comment by maxgalbu** [comment]
Thanks, I'll check it out

**Comment by maxgalbu** [comment]
@nzeppos

Please try the "latest" build from the releases page here on github. Install it using "install from zip file" from kodi

**Comment by nzeppos** [comment]
Works perfectly fine, fantastic! Thanks a lot!
