### ISSUE TITLE
Video not playable

### ISSUE THREAD

**Issue by Yaya7** [maxgalbu/xbmc.plugin.video.nba#20]
Hi I tried The first Gamein preseason but not working 
Can u fix it please

**Comment by nzeppos** [comment]
Same bug here. Trying to watch the live game and the request throws the usual error "Failed to find URL are you logged in etc".

It seems the latest update (0.8.3) fixed the issue with Archived games and NBA TV failing to retrieve the proper URL, but now we have a problem with live games.

**Comment by maxgalbu** [comment]
Yes, i couldn't test the live games when i released the fiz because there were none :) let me see if i still have the league pass from the previous season

**Comment by nzeppos** [comment]
Doesn't seem to only be affecting live games, but also the most recently archived ones. Meaning the same error is thrown for the two games from last night, which were the first of this season.

**Comment by jaydee73** [comment]
@maxgalbu There is a free trial for Global games at the moment. Maybe you can use this free subscription to do some testing?!

**Comment by maxgalbu** [comment]
There's this `gs` param in the request that changes, it's "3" for old games and "2" for new games, but currently even the websites returns "400 bad request" for the 2015/2016 games... I'll wait until it works before making changes

**Comment by Yaya7** [comment]
Try archive Game Not working  too
there Shanghai Sharks @ Houston Rockets  today we need to watch it pls

**Comment by Xanthurum01** [comment]
first of all, big thx to maxgalbu for making such a usefull addon!!! I'm using this since almost 2 years now, appreciate your work, your hours of sparetime!
In my mind, fixing this issue is not as crucial as it seems, the games are still preseason and at least we could use a pc to watch the games if it is that urgent. Of corse it would be nice to have it working now, but take your time for your work to be done well.
THX and Cheers

**Comment by Yaya7** [comment]
Hi  maxgalbu I see now The leafue pass in site Official works  if u want to make some chnages u can do it ,ow if u want  or next time i just noticed u  Thnx 
will continue watching in official website till this great addons get fixed yay ;)

**Comment by nzeppos** [comment]
Checked just now and both all archived games from last week work fine. Since the addon wasn't updated, I take it that NBA may have fixed/changed something on their side?

**Comment by Yaya7** [comment]
Yeah arachive game last week works now  But Live Not yet ;)

**Comment by justdre4327** [comment]
Archives from this week work as well now! For me at least

**Comment by maxgalbu** [comment]
I probably fixed, but it still doesn't work for some games... Is anybody with a paid subscription (not the free one i have now) able to see this match? https://watch.nba.com/game/20161003/UTAPOR

**Comment by maxgalbu** [comment]
I've pushed the commit that should partially fix the issue, download the zip file here: https://github.com/maxgalbu/xbmc.plugin.video.nba/releases/download/latest/plugin.video.nba-latest.zip

**Comment by nzeppos** [comment]
https://watch.nba.com/game/20161003/UTAPOR works perfectly fine with your addon (0.8.3), both the home feed stream and the condensed game (the away feed throws the usual Failed to get URL error but I doubt that stream is available at all).

**Comment by Yaya7** [comment]
Thanks maxgalbu Its working great Now 

you're  the best

**Comment by maxgalbu** [comment]
@nzeppos are you able to watch it on watch.nba.com too?

**Comment by nzeppos** [comment]
Yes, works on the official desktop site as well. Can't see any 400 errors on Firebug.

Another thing to note is that despite all these recently archived videos stating 60fps on Kodi info display when using your addon, it doesn't "feel" like 60fps at all. I tried some from last season and they're 60fps alright, motion is very smooth. This year everything feels like 30fps but shows 60 for whatever reason. I take it it may be an NBA thing? I think it was also mentioned in http://forum.kodi.tv/showthread.php?tid=124716&page=35

Anyway, off to donate now :)

**Comment by maxgalbu** [comment]
@nzeppos ok, it's my free account then :/

For the 60fps thing, the plugin will fall back to the lower quality video if it doesn't find the quality requested - it will go from 4500kbps (60fps) to 3000/1600/800/etc. so it's normal :)

**Comment by nzeppos** [comment]
According to Kodi, I AM sourcing the 4500kbps stream and the same display shows 60fps. And in the addon logs I can see that:

> 00:55:03 T:6748  NOTICE: DVDPlayer: Opening: http://nlds120.cdnak.neulion.com/nlds_vod/nba/vod/2016/10/03/11600008/9da239/1_11600008_uta_por_2016_b_whole_1_4500_ipad.mp4.m3u8 ...

But in reality it's 30fps. I checked some games from last season and the difference is obvious.

**Comment by nzeppos** [comment]
https://github.com/maxgalbu/xbmc.plugin.video.nba/releases

Confirming that the latest update seems to have fixed the issue with live games, I'm now watching Magic@Cavaliers. Again Kodi info shows bitrates of 3.5-4.5Mbps at 60fps but the actual stream isn't really 60fps.

**Comment by justdre4327** [comment]
@maxgalbu Every recorded game (e.g. full and condensed) have this issue on my end. Tried it with the newest release of your app just in case, the issue persists.

**Comment by maxgalbu** [comment]
As soon as I'll buy the league pass, I'll investigate. As of now every game is not playable from my free account.

**Comment by besarbb** [comment]
"game ended" screen today for the Cavs-Wizards game stayed way too long. It's still like that actually. Even though the game is available in VOD in nba.com, the add-on only shows "game ended" frame. This also happens with quite some games apart from this. Hopefully it's something that can be fixed in a way that the games would be available in kodi as soon as they are in nba.com.

Thanks for the great work put into this :)

**Comment by maxgalbu** [comment]
@besarbb please refer to issue #15

**Comment by justdre4327** [comment]
To add to my last reply, I turned on the debugger and every 10 seconds or so the frame rate goes from 60 to 30 FPS. It's still only on my PC, on my Android phone it works great.

**Comment by maxgalbu** [comment]
To all the users commenting in this issue, please open another issue if you still have problems. This issue is getting hard to track, so I'm closing it
