### ISSUE TITLE
Team Logo are blurry and sometimes incorrect

### ISSUE THREAD

**Issue by Miss80** [maxgalbu/xbmc.plugin.video.nba#25]
Th quality of the logo's  are not of best quality see also the attached screenshot (see also kodi forum).
[https://s14.postimg.org/kutc9a2gh/2016_10_11.png](url)

Furthermore, the logo of the hornets is shown which is correct, but the description of the game is mentioning Timberwolves.

**Comment by maxgalbu** [comment]
Yep these icons are best viewed in list mode. They're taken from the nba website, this is the code where the url is:

https://github.com/maxgalbu/xbmc.plugin.video.nba/blob/0f08e194a21ac28213a489f14a1520ee283a9587/games.py#L239

If you find another source for those images, please let me now. Feel free to make a pull request too :)

**Comment by maxgalbu** [comment]
Examples:

- http://e1.cdnl3.neulion.com/nba/player-v4/nba/images/teams/POR.png
- http://e1.cdnl3.neulion.com/nba/player-v4/nba/images/teams/SAS.png

It would have to be a similar url, with the team as variable in the url, or at the minimum a list of teams with their correspondent images

**Comment by Miss80** [comment]
Will this work (sorry I'm new at this)? 

https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Boston_Celtics.svg/480px-Boston_Celtics.svg.png

If so, let me know, I'll make a list for you.

**Comment by maxgalbu** [comment]
Well done, the file from wikipedia looks good, especially because it has transparency, the second link doesn't have transparency and will look bad on kodi. Don't worry about the url composition, I can have a mapping between team and image. You can upload it wherever you want, but it must be online all the time and with a direct access (eg not dropbox)

Anyway, if you can make a list of images and corresponding teams, I can integrate it

**Comment by Miss80** [comment]
I've downloaded all logo's and placed them on a public folder on imgur:

http://imgur.com/a/tIhcX

I need to find a new logo for the philadelphia 76ers. That one wasn't available via the website that I used. 
Let me know if you need anything else

**Comment by maxgalbu** [comment]
Thanks a lot! There were some incorrect logos, like the pelicans were "hornets" and the hornets were "bobcats", and brooklyn had some part without alpha channel. When I went looking for replacements I found a resource with bigger images:

http://i.cdn.turner.com/nba/nba/.element/img/1.0/teamsites/logos/teamlogos_500x500/nop.png
http://i.cdn.turner.com/nba/nba/.element/img/1.0/teamsites/logos/teamlogos_500x500/phi.png

Thanks anyway :) I saved the links to your images here: https://gist.github.com/maxgalbu/975295d07809203bdff69a40f0315910

**Comment by ivankokan** [comment]
Are these *http://i.cdn.turner.com... images in the plugin now? Since which release?

**Comment by Miss80** [comment]
Yes, Max implemented those two months ago

**Comment by ivankokan** [comment]
@Miss80 @maxgalbu But still not available in the official release?

**Comment by Miss80** [comment]
As far as I'm aware it is. Here the latest version is working perfectly.

**Comment by ivankokan** [comment]
I have 0.8.4 installed, is this the latest numbered official release?

**Comment by Miss80** [comment]
Not sure if it's the official release. I have installed the version from github and that is indeed 0.8.4. I just checked again, and my logo's are good.

**Comment by ivankokan** [comment]
Nightly master (Nov 21, 2016) works correctly. However, it's newer than the original 0.8.4 (Oct 29, 2016) release which seems to be the official one.
