### ISSUE TITLE
Error Connect Live Games

### ISSUE THREAD

**Issue by yzfr1** [maxgalbu/xbmc.plugin.video.nba#26]
i used saturday night (10/15)  the plugin to watch a live game and error -> Failed to get a video URL - Are you logged in??? but i access to webpage and see OK, i try in nba app of mobile android and run OK. The user y pass of plugin is well because i enter good in webpage and android. But the strange is what when go to archive games through the plugin can see OK.

Maybe, nba change something to streaming live games.

**Comment by maxgalbu** [comment]
This could be related to #20...

**Comment by leaguepassman20** [comment]
I'm getting the same problem :/

**Comment by maxgalbu** [comment]
Please let me know if it still has issues with the latest version (0.8.4)
