### ISSUE TITLE
Watching live games in delay

### ISSUE THREAD

**Issue by olevitzky** [maxgalbu/xbmc.plugin.video.nba#27]
Hi, first thanks for this amazing addon!

I have an issue when I want to start watching the game an hour late but from the beginning of course. I see that this is not possible so the only thing I can do is wait about 3 hours until the game show up on the archive games list.

a) Is there a way to watch 'live' games but in delay?
b) Do I really need to wait 2-3 hours after the game ends until I can watch the full game?

Thanks

**Comment by maxgalbu** [comment]
I'm tracking this issue in #15
