### ISSUE TITLE
can this addon work for US league pass subscription?

### ISSUE THREAD

**Issue by sarbel1** [maxgalbu/xbmc.plugin.video.nba#28]

**Comment by maxgalbu** [comment]
see #24

**Comment by sarbel1** [comment]
hey
can i install tunnelbear on openelec kodi?

btw i can gove you usa account to test

**Comment by maxgalbu** [comment]
@sarbel1 let me know about your account via email...

**Comment by sarbel1** [comment]
whats your email?

**Comment by maxgalbu** [comment]
See my profile on github

**Comment by crotoc** [comment]
I have a US account and it always shows "Failed to find video URL, are you logged in". Have you guys fixed it?

**Comment by crotoc** [comment]
Do you guys solve the problem?

**Comment by maxgalbu** [comment]
It's not as easy as it looks, it's a completely different flow
