### ISSUE TITLE
720p/60 and away feed error

### ISSUE THREAD

**Issue by yzfr1** [maxgalbu/xbmc.plugin.video.nba#29]
I try with opening night games, and see all at 29.970 fps.   Someone can play 720p at 60fps???

**Comment by iosonofrancesco** [comment]
yep, they switched to an higher framerate, it's fixable changing from 4500 to 6000 on available bitrate.

**Comment by yzfr1** [comment]
yes, bitrate i saw that sometimes have more 5000 and other times less 4000, is like a variable bitrate. Away feed not work for me too. I try with two news releases and still with error of login in away feed.

**Comment by iosonofrancesco** [comment]
you can fix editing the common.py at line 14

` (72060, 6000),`

you should get the home feed at 60fps

**Comment by yzfr1** [comment]
ok, i will try...
