### ISSUE TITLE
Installation failed on common plugin cache and Failed to install a dependency

### ISSUE THREAD

**Issue by Hamozus** [maxgalbu/xbmc.plugin.video.nba#31]
Hi,
When I try to install the add-on be it from a downloaded zip file or from the depository, i get these two errors. 
They appear whether I am using Kodi 16.1 or 17.0 beta. 
I'm using mac OSX 10.12.1

**Comment by maxgalbu** [comment]
Just tested on a fresh installation of Kodi 16.1, it works. If you installed 17 beta first, this could be your issue: http://forum.kodi.tv/showthread.php?tid=150985
