### ISSUE TITLE
choice of home or away feed not available

### ISSUE THREAD

**Issue by Miss80** [maxgalbu/xbmc.plugin.video.nba#32]
When trying to watch the game celtics - hornets (10/29), there was no choice of away or home feed. Only the home feed was available when pressing' full game'. Both feeds were available on the website.
When checking grizzlies - knicks, we could chose

**Comment by maxgalbu** [comment]
When there's no choice there's only the home feed.
Currently i see they are both available... for pretty much all games. Probably there was a live feed available, but no archive game for the away feed.
