### ISSUE TITLE
Can we get National TV versions of the match?

### ISSUE THREAD

**Issue by besarbb** [maxgalbu/xbmc.plugin.video.nba#33]
I wish there was also the option for national tv broadcast when available. For example, last night Nets @ Knicks and Rockets @ Spurs was on ESPN, but this add-on only gives the option of home or away feeds.

Is this feasible? Thanks :)

**Comment by maxgalbu** [comment]
Hmm I

**Comment by itzeddie** [comment]
This appears to of broken away feeds, also can't seem to get these alternate feeds to work on VOD?
