### ISSUE TITLE
Latest Nightly - Away Feeds

### ISSUE THREAD

**Issue by itzeddie** [maxgalbu/xbmc.plugin.video.nba#34]
Hey Max,

The latest nightly appears to of removed the option of the away feed completely, also the alternate cameras don't appear to be working.

Cheers,
Eddie

**Comment by maxgalbu** [comment]
Which nightly version? dev or master?

**Comment by itzeddie** [comment]
Sorry, dev nightly, where you added the alternate cameras.

**Comment by maxgalbu** [comment]
you're right, fixed in 66172ea6c6ef4729a661cc5b1307fa09a27a7ada, thanks
