### ISSUE TITLE
Feature request. View other feeds

### ISSUE THREAD

**Issue by angus1225** [maxgalbu/xbmc.plugin.video.nba#35]
Can we have the other feeds like the Spanish one?
Thanks a lot.
Very good work

**Comment by maxgalbu** [comment]
I've already developed it for #33, you can download the dev version:

https://github.com/maxgalbu/xbmc.plugin.video.nba/releases/download/nightly-dev/plugin.video.nba-dev.zip

**Comment by besarbb** [comment]
Is anything being done about the "Game ended" max? I've been waiting for at least a reply about whether there can be done something or not.

**Comment by maxgalbu** [comment]
This has now been merge into master, and will be released soon in 0.9 version
