### ISSUE TITLE
Plugin ignoring the quality option.

### ISSUE THREAD

**Issue by EvO-E** [maxgalbu/xbmc.plugin.video.nba#38]
You know how on watch.nba.com you can select bitrate etc? Here i'm selecting 800kbps and it's going full 720p which kills my internet. Fix the quality issue pelase. It is super important for me as this is the only way to watch nba tv

**Comment by EvO-E** [comment]
Even ignoring it on Streams as well

**Comment by maxgalbu** [comment]
Are you referring to live or archive games?

**Comment by EvO-E** [comment]
NBA tv live

**Comment by maxgalbu** [comment]
I'm not reproducing this issue. With #54 merged, you should be able to select "auto" as quality and let ffmpeg/kodi decide for you. Let me know if it works for you
