### ISSUE TITLE
No new episodes of Shaqtin'a fool

### ISSUE THREAD

**Issue by jaydee73** [maxgalbu/xbmc.plugin.video.nba#40]
I cannot find 2017 episodes of Shaqtin'a fool with the Add-on. The last found episode is from December 2016.

But 2017 episodes seem to exist, because I have found them trough other web sources.

Is this a problem of the Add-on? Or from the Neulion source?

**Comment by maxgalbu** [comment]
There's a problem in the search endpoint i'm using, i'll try to work around it

**Comment by maxgalbu** [comment]
I didn't find any alternative, but apparently it fixed itself... someone in the nba staff started using tags again
