### ISSUE TITLE
Playback just stops randomly

### ISSUE THREAD

**Issue by airadam** [maxgalbu/xbmc.plugin.video.nba#41]
I've been using this on both a Windows 7 PC and a Raspberry Pi 3, and on both versions playback will often just stop and kick me back to the add-on menu. There's no error message or other feedback, and no sign that a stoppage is coming. This is most noticeable when trying to watch NBA TV live.

**Comment by airadam** [comment]
More detail - I'm watching NBA Gametime on "Today's Programming", and it stops playing almost exactly every five minutes.

**Comment by airadam** [comment]
Playback appears to stop at 4:43 each time

**Comment by maxgalbu** [comment]
I know this issue and I couldn't find a solution some months ago. Please refer to issue #16
