### ISSUE TITLE
Video Smoothness

### ISSUE THREAD

**Issue by Xanthurum01** [maxgalbu/xbmc.plugin.video.nba#44]
Just wondering about smoothness on playback...
If you look at the Hawks-Spurs game from 2017-03-13 the video plays perfectly smooth, you can absolutely notice the difference! All the other games don't. I didn't see the live game of this one but I guess it had the same quality.
Does this videoquality come from NBA's side (encoded video) or is it a issue with my Setup of Kodi or the addon itself?
If it is on my end: If someone can tell me how to optimize the videoquality please feel free to do so... ;-)

(And if I remember correctly all the games from the previous season had the same Quality as the on above)

THX

**Comment by nzeppos** [comment]
Sadly this "smoothness" is nothing but a pure 60fps stream coming straight from Neulion (the NBA LP crap provider). The current Kodi addon by default aims to source 60fps mp4 streams (if available) but has no real control over the **actual** frame rate of the video provided by Neulion.

Meaning that until last year, **all** such videos were true 60fps. But from 2016-17 onwards, the vast majority may be advertised as 60 fps but in truth they are not (ie. Neulion provides a stream output of 60fps but the input is NOT 60fps like it used to be last year). You can check the frame rate that by pressing "O" (omicron) on Kodi 16 or control+shift+O on Kodi 17+. If you do that, observe how both the Hawks-Spurs video from 2017-03-13 and all other videos from that date display as 60fps, but only the former one is true 60fps (ie. real smooth). The rest are effectively 30fps.

There's nothing to be done about this. Even AppleTV users are facing the exact same issue. Hopefully next year Neulion will come to their senses and fix this.

**Comment by maxgalbu** [comment]
Yep, unless someone finds an additional bitrate for actual 60fps in the bitrates available, this is all we're gonna get this year.

**Comment by Xanthurum01** [comment]
Sorry for the late reply, I was on vacation!

Oh bad! At least for the tons of money they get from league pass owners such like us, they could have provided true 60 fps! Greedy bas***ds :-)

Thanks for investigating to both of you, keep this beautiful addon shining!

Cheers
