### ISSUE TITLE
National TV feeds in playoff matches are missing

### ISSUE THREAD

**Issue by jaydee73** [maxgalbu/xbmc.plugin.video.nba#45]
Hey maxgalbu,

now, as the playoffs have begun, every game is available with multiple feeds. At least when I watch the games through the website. Home & away feed along with national TV feed (TNT, ABC etc.). In your plugin there's only the usual home & away feed. I've seen this for example with CHI@BOS Game 1. No chance to see the TNT feed with your plugin atm.

Is there any chance to modify your plugin to also offer the national feeds? 

Thanks!

Regards,
JayDee

**Comment by maxgalbu** [comment]
See #35
