### ISSUE TITLE
Stopped working 

### ISSUE THREAD

**Issue by angus1225** [maxgalbu/xbmc.plugin.video.nba#46]
Today stopped working. 
I tried to see bulls.celtics but i can't. 
Yesterday was working like a charm as always. 
Something changed today
Sorry for my English...I'm from Uruguay
Thanks for this big addon!!

**Comment by orenh1** [comment]
I'm seeing this too: the plugin stopped playing archived streams about 10 hours ago. It was working fine right up to that point. Now, when I try to play an archived stream it says "Working..." for a while, and then shows this error: "One or more items failed to play".

However, it's still playing Highlight streams. So I suspect that this has something to do with streams that require an NBA League Pass account. (Which I have, of course: I can play the streams fine using the NBA League Pass Android app. But this plugin provides a much better playback experience than the official app, so I'd rather use it). Alternatively, perhaps the Highlights are still working because they're so much shorter than the full games?

**Comment by angus1225** [comment]
You are describing exactly what i noticed. 
I also have a working nba league pass account.
I use the addon because the nba app don't work fine in my smart tv.

**Comment by irandhal** [comment]
Same problem, i have a league pass account, everything worked fine until yesterday, only highlight still working now :(

**Comment by elschmidtorado** [comment]
Thats from the logfile:

in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
10:29:30.895 T:3918295968 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
10:29:30.906 T:3765203872 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
10:29:30.906 T:3765203872 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
10:29:30.909 T:3926684576 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
10:29:30.909 T:3926684576 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
10:29:33.077 T:4120920640 NOTICE: VideoPlayer: Opening: http://nlds120.cdnak.neulion.com/nlds_vo...id=5513231
10:29:33.077 T:4120920640 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:29:33.097 T:3884098464 NOTICE: Creating InputStream
10:29:33.232 T:3884098464 NOTICE: Creating Demuxer
10:30:03.338 T:3884098464 ERROR: OpenDemuxStream - Error creating demuxer
10:30:03.339 T:3884098464 NOTICE: CVideoPlayer::OnExit()
10:30:03.346 T:4120920640 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed]
10:30:03.353 T:4120920640 NOTICE: CVideoPlayer::CloseFile()
10:30:03.354 T:4120920640 NOTICE: VideoPlayer: waiting for threads to exit
10:30:03.354 T:4120920640 NOTICE: VideoPlayer: finished waiting
10:30:03.354 T:4120920640 NOTICE: CVideoPlayer::CloseFile()
10:30:03.354 T:4120920640 NOTICE: VideoPlayer: waiting for threads to exit
10:30:03.354 T:4120920640 NOTICE: VideoPlayer: finished waiting
10:30:08.881 T:3884098464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
10:30:08.881 T:3884098464 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
10:30:08.883 T:3884098464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
10:30:08.883 T:3884098464 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
10:30:08.885 T:3884098464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
10:30:08.886 T:3884098464 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
10:33:44.820 T:4120920640 ERROR: GetDirectory - Error getting plugin://plugin.video.nba/?mode=archive&name=Archive&url=archive
10:33:44.825 T:4120920640 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nba/?mode=archive&name=Archive&url=archive) failed
10:34:30.391 T:4120920640 NOTICE: Storing total System Uptime
10:34:30.391 T:4120920640 NOTICE: Saving settings
10:34:30.402 T:4120920640 NOTICE: Saving skin settings
10:34:30.407 T:4120920640 NOTICE: stop all
10:34:30.407 T:4120920640 NOTICE: stop player
10:34:30.407 T:4120920640 NOTICE: ES: Stopping event server
10:34:30.466 T:4120920640 NOTICE: stopping upnp
10:34:30.617 T:4120920640 NOTICE: stopping zeroconf publishing
10:34:30.625 T:4120920640 NOTICE: CWebServer[8080]: Stopped
10:34:31.380 T:3802268576 NOTICE: ES: UDP Event server stopped
10:34:31.382 T:4120920640 NOTICE: stop dvd detect media
10:34:34.429 T:4120920640 NOTICE: clean cached files!
10:34:36.498 T:4120920640 NOTICE: closing down remote control service
10:34:36.500 T:4120920640 NOTICE: stopped
10:34:36.714 T:4120920640 NOTICE: destroy
10:34:36.714 T:4120920640 NOTICE: unload skin
10:34:36.814 T:4120920640 WARNING: Cleanup: Having to cleanup texture lists/focus.png
10:34:36.814 T:4120920640 WARNING: Cleanup: Having to cleanup texture overlays/shadow.png
10:34:36.815 T:4120920640 WARNING: Cleanup: Having to cleanup texture dialogs/dialog-bg-nobo.png
10:34:36.815 T:4120920640 WARNING: Cleanup: Having to cleanup texture overlays/badge.png
10:34:36.815 T:4120920640 WARNING: Cleanup: Having to cleanup texture colors/grey.png
10:34:36.863 T:4120920640 NOTICE: unload sections
10:34:36.878 T:4120920640 NOTICE: special://profile/ is mapped to: special://masterprofile/
10:34:36.882 T:4120920640 NOTICE: application stopped...

**Comment by carnifun** [comment]
Same problem hier ..
Seem like the path to the archive files has changed ? 
 ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed

**Comment by irandhal** [comment]
My log file  

00:02:38 T:2352 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
00:02:38 T:2352   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
00:02:38 T:2352 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
00:02:38 T:2352   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
00:02:38 T:2352 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
00:02:38 T:2352   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
00:02:41 T:3376  NOTICE: DVDPlayer: Opening: http://nlds120.cdnak.neulion.com/nlds_vod/nba/vod/2017/04/18/41600172/141f3b/3_41600172_uta_lac_2016_b_whole_1_6000_ipad.mp4.m3u8?hdnea=expires%3D1492639477%7Eaccess%3D%2Fnlds_vod%2Fnba%2Fvod%2F2017%2F04%2F18%2F41600172%2F141f3b%2F*%7Emd5%3D2650b64a42a41d24ea2f41d921018c8a&nltid=nba&nltdt=6&uid=3335927
00:02:41 T:3376 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
00:02:41 T:508  NOTICE: Creating InputStream
00:02:41 T:508  NOTICE: Creating Demuxer
00:02:41 T:508   ERROR: CCurlFile::GetCookies - invalid cookie: '.neulion.com	TRUE	/	FALSE	0	nlq	'
00:02:41 T:508   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.thetvdb.com	TRUE	/	FALSE	1498566709	__cfdu	'
00:02:41 T:508   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.thetvdb.com	TRUE	/	FALSE	1498566709	_	'
00:03:11 T:508   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
00:03:11 T:508  NOTICE: CDVDPlayer::OnExit()
00:03:11 T:3376   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed]
00:03:11 T:3376  NOTICE: CDVDPlayer::CloseFile()
00:03:11 T:3376  NOTICE: DVDPlayer: waiting for threads to exit
00:03:11 T:3376  NOTICE: DVDPlayer: finished waiting
00:03:11 T:3376  NOTICE: CDVDPlayer::CloseFile()
00:03:11 T:3376  NOTICE: DVDPlayer: waiting for threads to exit
00:03:11 T:3376  NOTICE: DVDPlayer: finished waiting
00:03:13 T:1148 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
00:03:13 T:1148   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=1&video_type=archive&name=Full+game%2C+home+feed
00:03:13 T:1148 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
00:03:13 T:1148   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_type=condensed&name=Condensed+game
00:03:13 T:1148 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed
00:03:13 T:1148   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=3&mode=playgame&url=&video_id=0041600172&video_ishomefeed=0&video_type=archive&name=Full+game%2C+away+feed

**Comment by maxgalbu** [comment]
Looking at it right now... it's a mess because the streams are cookie protected :( highlights works because they don't require authentication

**Comment by quasmaster** [comment]
Same here. Thanks for looking into the issue!! One other question. Since I had to switch to alternative viewing devices, I noticed that in the browser and on the official mobile apps there are more feeds to choose from. So besides the "Home", "Away", "Condensed" and "Highlight" feeds, there are also television feeds by TNT, ESPN, etc. available for some games. Would it be possible to access those feeds via your Kodi addon as well?

**Comment by furkyto** [comment]
maxgalbu is any chance to fix it.... ?:)

**Comment by maxgalbu** [comment]
Unfortunately to find a solution it's basically trial and error, not something quick

**Comment by angus1225** [comment]
Thanks a lot for your work and effort!

**Comment by kaileu** [comment]
@maxgalbu the fix is easy but i didn't find the time for an PR.
The Keyserver blocks the Kodi Useragent you have to pass a different Useragent to ffmpeg.

**Comment by nickomaru** [comment]
`you have to pass a different Useragent to ffmpeg in common.py`
i not found this

**Comment by woronczak** [comment]
Not sure if it helps any, but the addon still works fine in SPMC

**Comment by kaileu** [comment]
They block the standard Useragent from  Kodi.
Spmc may use a diffrent Useragent.
You didn't find a useragent there you have to add it to the URL from the stream.
The easiest Solution is with + '| useragent=blabla'

**Comment by nzeppos** [comment]
Can confirm that the pull request proposed in issue #48 works OK.

**Comment by WHamilton** [comment]
Which file I must change?

**Comment by kaileu** [comment]
common.py or games.py 
Look at https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/48/files

**Comment by WHamilton** [comment]
I ve changed line 81 in  .kodi/addons/plugin.video.nba/games.py

but same error.

Must I reboot?

**Comment by kaileu** [comment]
Normally you only has to restart the addon.

**Comment by WHamilton** [comment]
I don't what is wrong. After reboot the same issue.
I am using kodi 16.1

**Comment by WHamilton** [comment]
There was a second folder on my System

/.kodi/addons/xbmc.plugin.video.nba-master

games.py changed and works fine. For archived games.

**Comment by furkyto** [comment]
I didn't understand where exactly have to add this selected_video_url = "%s|User-Agent=iTunes-AppleTV/4.1" % getGameUrlWithBitrate(url, video_type)  or I have to replace some line with it , please explane me .... Can I edit the games.py file with notepad++?

**Comment by WHamilton** [comment]
You must change line 81.

**Comment by furkyto** [comment]
It works for archive games , thank you very much , very very healthy live :)

**Comment by elschmidtorado** [comment]
yeeeees, thx a lot for the half fix of the problem :-) 
The archive is working .......  what about the live games :-) ?????

**Comment by WHamilton** [comment]
live games not working

**Comment by furkyto** [comment]
Can you help me , how can I record live games with kodi nba league pass , is there any way to do that ?

**Comment by nzeppos** [comment]
@WHamilton on the contrary, live games are working perfectly fine after applying the changes proposed in https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/48/files

@furkyto this recording feature is already covered in https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/13, but my guess is that it's not very likely to happen in the near future

**Comment by quasmaster** [comment]
Made the suggested changes in the 4 files by hand and everythings is up and running again! YAY! THANKS!! Playoff time!!

**Comment by maxgalbu** [comment]
This fix is now included in the nightly version build by travis: https://github.com/maxgalbu/xbmc.plugin.video.nba/releases/download/nightly-master/plugin.video.nba-master.zip

(you can install it from kodi via "Install from zip")

I will try to fix some other bugs like cameras and nba tv live before releaseing a new version

**Comment by tzach** [comment]
Thanks for the great work
I have the same issue. When trying to install the latest from zip I get

```
03:59:05.674 T:140541317134080   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'file' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/home/tzach/.kodi/addons/plugin.video.nba/src/service.py", line 116, in <module>
                                                main()
                                              File "/home/tzach/.kodi/addons/plugin.video.nba/src/service.py", line 97, in main
                                                shared_data.set("playing", {})
                                              File "/home/tzach/.kodi/addons/plugin.video.nba/src/shareddata.py", line 24, in set
                                                json_content = self.__getFileContent()
                                              File "/home/tzach/.kodi/addons/plugin.video.nba/src/shareddata.py", line 19, in __getFileContent
                                                file.close()
                                            UnboundLocalError: local variable 'file' referenced before assignment
                                            -->End of Python script error report<--
03:59:05.703 T:140541317134080    INFO: Python script stopped

```

**Comment by tzach** [comment]
Look like #43 
Is the fix part of the zip?
