### ISSUE TITLE
PLZ Help - the playoffs just began and the add on isnt workin anymore - i posted in the KodiForum the logfile!!!

### ISSUE THREAD

**Issue by elschmidtorado** [maxgalbu/xbmc.plugin.video.nba#47]

**Comment by nzeppos** [comment]
I guess this is the same issue as the one already experienced by virtually all addon users: https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/46

**Comment by maxgalbu** [comment]
Yes, please refer to 46
