### ISSUE TITLE
Late start of archive games

### ISSUE THREAD

**Issue by furkyto** [maxgalbu/xbmc.plugin.video.nba#57]
Hello i'm from Bulgaria and i have problem with archive games , I can't play them very later after they are allready finished , when i try to open the game it start a video with Game Has Ended and this is 5 hours after the games are finished in USA .When i enter NBA.com with League pass from the browser the games starts.Can you help me with this pretime of Kodi

**Comment by furkyto** [comment]
Only one archive game starts about 12 hours after the games are finished from the last night . Any help ?

**Comment by furkyto** [comment]
10:12:49.319 T:11748  NOTICE: VideoPlayer: Opening:
10:12:49.319 T:11748 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:12:49.393 T:12868  NOTICE: Creating InputStream
10:12:49.495 T:12868   ERROR: perror:
10:12:49.495 T:12868   ERROR: Error on dvdnav_open
10:12:49.495 T:12868   ERROR: CVideoPlayer::OpenInputStream - error opening []
10:12:49.495 T:12868  NOTICE: CVideoPlayer::OnExit()
10:12:49.495 T:11748   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nba/?game_state=2&name=Full+game&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000]
10:12:49.497 T:11748  NOTICE: CVideoPlayer::CloseFile()
10:12:49.497 T:11748  NOTICE: VideoPlayer: waiting for threads to exit
10:12:49.497 T:11748  NOTICE: VideoPlayer: finished waiting
10:12:49.497 T:11748  NOTICE: CVideoPlayer::CloseFile()
10:12:49.497 T:11748  NOTICE: VideoPlayer: waiting for threads to exit
10:12:49.497 T:11748  NOTICE: VideoPlayer: finished waiting
10:12:49.501 T:11304 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=2&name=Full+game&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:49.501 T:11304   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=2&name=Full+game&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:49.502 T:1580 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=2&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:49.502 T:1580   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=2&name=Camera+12%3A+Audio+Home&camera_number=12&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:49.503 T:11304 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?game_state=2&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:49.503 T:11304   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?game_state=2&name=Camera+16%3A+Mobile+View&camera_number=16&url=&start_time=None&video_id=0011700048&video_type=archive&mode=playgame&duration=8638000
10:12:50.423 T:3484   ERROR: EXCEPTION: XBMC is not playing any file


This is what is says when i'm trying to open games from last night and in Kodi it says me "Failed to ger video url. Are you logged in?" and this is from satuday's game i can't play any games from saturday till today

**Comment by furkyto** [comment]
Ooooo a recover it with https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/ca6d71dac8fc2a7d8f73f53c54252fdf364316be

**Comment by maxgalbu** [comment]
Yep, we're continuing here: https://github.com/maxgalbu/xbmc.plugin.video.nba/issues/55
