### ISSUE TITLE
re-stream using ffmpeg

### ISSUE THREAD

**Issue by jrzv84** [maxgalbu/xbmc.plugin.video.nba#59]
Hello,

I have an international nba active account and wonder if you can help me to allow me re-stream the live playing games using ffmpeg...

thanks in advance

**Comment by maxgalbu** [comment]
Not sure since we now have a DRM decrypter as middleware. Not sure about legal issues also...

**Comment by maxgalbu** [comment]
Not sure since we now have a DRM decrypter as middleware. Not sure about legal issues also...

**Comment by maxgalbu** [comment]
Not sure since we now have a DRM decrypter as middleware. Not sure about legal issues also...

**Comment by maxgalbu** [comment]
Not sure since we now have a DRM decrypter as middleware. Not sure about legal issues also...
