### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by siggijo72** [maxgalbu/xbmc.plugin.video.nba#6]
Hi,
Didn't know where else to issue a feature requests, hope it's okay.

1. Would like to see the highlights on the first page, where they were. Click on date and watch highlights on that date. Now kinda hidden in the archive and finding them counterintuitive in my opinion.
2. NBA.com specials like Shaqtin a fool, The Starters, etc. 
3. NBA TV on demand, list of programs from the NBA tv channel, if that's possible
4. Access to the vault on NBA TV.

Thats it, great addon btw. I'm a big fan of your work. Trying to become a pythonista but still a noob. Can't understand 90% of your code (lack of comments don't help but no biggie). Keep it up, your'e awesome!!!

Best regards,
Siggi from Iceland

**Comment by maxgalbu** [comment]
Yeah, here's ok :)

> Would like to see the highlights on the first page, where they were. Click on date and watch highlights on that date. Now kinda hidden in the archive and finding them counterintuitive in my opinion.

I'm following what the app and the website does, in this way you can see the highlights for every game in the past, not just the previous week. I'm not keen to change it, i like being able to choose what to watch, if condensed or highlight

> NBA.com specials like Shaqtin a fool, The Starters, etc.

This could be interesting, I'll take a look

> NBA TV on demand, list of programs from the NBA tv channel, if that's possible
> Access to the vault on NBA TV.

This is limited to premium league pass, isn't it? Unfortunately I don't have it :/

**Comment by siggijo72** [comment]
Can you use my subscription if I buy one? Or is there geoip restrictions?

**Comment by maxgalbu** [comment]
I honestly don't know, but I have an unlimited subscription to the tunnelbear VPN so it shouldn't be a problem

**Comment by siggijo72** [comment]
Thanks for shaqtin the fool. One more suggestion; Smittys top play under the rim.
