### ISSUE TITLE
Can't play (can't download keys)

### ISSUE THREAD

**Issue by magnusjjj** [maxgalbu/xbmc.plugin.video.nba#64]
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] request: GET [snipped].m3u8.key HTTP/1.1
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] User-Agent: iTunes-AppleTV/4.1
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] Accept: */*
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] Connection: close
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] Host: nlsk3.neulion.com
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] Cookie: [snipped]
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https] Icy-MetaData: 1
12:12:36.703 T:33892   DEBUG: ffmpeg[8464]: [https]
12:12:38.039 T:33892   DEBUG: ffmpeg[8464]: [https] header='HTTP/1.1 403 Forbidden'
12:12:38.039 T:33892   DEBUG: ffmpeg[8464]: [https] http_code=403
12:12:38.039 T:33892   DEBUG: ffmpeg[8464]: [https] HTTP error 403 Forbidden
12:12:38.040 T:33892   ERROR: ffmpeg[8464]: Unable to open key file [snipped].m3u8.key

**Comment by nickomaru** [comment]
on Kodi we are have a link
https://nlds120.cdnllnwnl.neulion.com/nlds_vod/nba3/vod/2017/10/21/nlncp/21700030/2_21700030_det_nyk_2017_**a_whole_1_**ipad.mp4.m3u8.............iTunes-AppleTV/4.1
(away comment)

We are edit this line 

https://nlds120.cdnllnwnl.neulion.com/nlds_vod/nba3/vod/2017/10/21/nlncp/21700030/2_21700030_det_nyk_2017_**b_whole_1_6000_**ipad.mp4.m3u8.........
(home)

**Comment by magnusjjj** [comment]
What are you talking about? This is a logfile from kodi, with all of the logging in the settings turned on.
This is why we can't play video. Neuelion changed something and returns 403 when downloading the encryption keys.

Could have to do with the code dumping all of the cookies except one, but working on it. :/

**Comment by maxgalbu** [comment]
DIscussing the same thing on #60
