### ISSUE TITLE
Top plays not working

### ISSUE THREAD

**Issue by siggijo72** [maxgalbu/xbmc.plugin.video.nba#7]
Top plays haven't worked for a week. List is empty.

**Comment by maxgalbu** [comment]
ok, i'll look, thanks :)

**Comment by maxgalbu** [comment]
Apparently they no longer put the right tag to the top plays videos, if you look on the video page (http://watch.nba.com/video) you'll see that the top plays tab's latest videos are the ones from the 18th of november. Let's see if I need to find a way around that, or they change their minds

**Comment by maxgalbu** [comment]
Found a workaround - latest version should work.
