### ISSUE TITLE
Stopped playing videos newer than 13.02

### ISSUE THREAD

**Issue by radaczynski** [maxgalbu/xbmc.plugin.video.nba#71]
Hi,

I assume that this a breaking change on the NBA website, but the plugin is playing highlight videos up until the highlights from 13.02. All the later videos are not starting and the error log says:
`07:23:53.188 T:1259557792   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=802340&mode=videoplay&name=Melhores+Momentos+-+Time+Stephen+vs+Time+LeBron+%2802%3A19%29+-+18%2F02%2F20
18
07:23:53.198 T:1259557792 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=801691&mode=videoplay&name=Melhores+Momentos+-+Desafio+dos+Calouros+%2802%3A28%29+-+
16%2F02%2F2018
07:23:53.198 T:1259557792   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=801691&mode=videoplay&name=Melhores+Momentos+-+Desafio+dos+Calouros+%2802%3A28%29+-+16%2F02%2F2018
07:23:53.203 T:1259557792 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=801779&mode=videoplay&name=GAME+RECAP%3A+2018+Mtn+Dew+Kickstart+Rising+Stars+%2802%3
A06%29+-+16%2F02%2F2018`

For the video from 13.02 the log says
`07:58:57.195 T:1943501264  NOTICE: VideoPlayer: Opening: https://nlds119.cdnllnwnl.neulion.com/nlds_vod/nbatv/vod/2018/02/13/20180212_sas_uta_recap/20180212_sas_uta_recap_1_pc.mp4.m3u8`

Is there anything to do to fix this?

**Comment by kinimod85** [comment]
i got the same problem -> all videos later than 13.2.2018 don't work.

is there a fix?

**Comment by utrotzek** [comment]
I've got the same problem ;-(

**Comment by radaczynski** [comment]
@maxgalbu: could you comment on the reason for closing it? I still have the same symptoms, the videos are not playing and the log still says the same:
`09:32:02.537 T:1251996576 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nba/?url=841365&mode=videoplay&name=Assist+of+the+Night%3A+Nikola+Jokic+%2800%3A15%29
09:32:02.537 T:1251996576   ERROR: InputStream: Error opening, plugin://plugin.video.nba/?url=841365&mode=videoplay&name=Assist+of+the+Night%3A+Nikola+Jokic+%2800%3A15%29`

Is the something I should do to fix this?

**Comment by radaczynski** [comment]
does e60a951ad4ae931d04aa0e5ced2b3c5fceb0bbc7 fix the issue?

**Comment by maxgalbu** [comment]
Nope, this commit https://github.com/maxgalbu/xbmc.plugin.video.nba/commit/c7c8a9168a88c623c5a9ecfffcb7c03ec765ce94

Please try the zip from the Releases here on github, if it still doesn't work, please reopen post Kodi version

**Comment by radaczynski** [comment]
There must have been multiple issues then. My issue got fixed by the e60a951, change in line 187. The release from master does work for me. 

Thanks a lot!
