### ISSUE TITLE
NBA

### ISSUE THREAD

**Issue by furkyto** [maxgalbu/xbmc.plugin.video.nba#73]
The Game Lakers vs Blazers from last night 05.03.2018 doesn't start

**Comment by furkyto** [comment]
It is Knicks vs Blazers game from last night that not start

**Comment by furkyto** [comment]
Raptors vs Pistons 07.03 still doesn't start

**Comment by cablegoon** [comment]
Miami vs Philly not working  live - the other two games play fine live. Been using the plugin for years and never had issues - I am assuming LP changed something on their end. 
Also never gotten the start from beginning button to work as intended mid-game  - not sure if that's a known issue - will open another ticket if others are having the same issue

**Comment by furkyto** [comment]
Yes for about one week every night one game doesn't work , maybe it is something about coockies .... they can't be passed i don't know but the games works in browser in nba.com/LP

**Comment by sam43434** [comment]
1 game a night they use a different encryption

**Comment by elmakal01** [comment]
greetings there is no update available for nba plugin

**Comment by maxgalbu** [comment]
Please try latest zip file in the Releases section here on github
