### ISSUE TITLE
Will only play games from this season, games from past seasons don't play in kodi

### ISSUE THREAD

**Issue by mtepper27** [maxgalbu/xbmc.plugin.video.nba#75]
I love your work Max. Thanks for all you do. 

I get this error when using a UK vpn and also without a vpn (US ip).  

Here is the pastebin:  https://pastebin.com/PxGz0RCC

Thanks for any help!

Windows 10, Kodi 17.6, I tried both NBA League Pass 1.0.0 and now I'm on 1.0.1

**Comment by Yaya7** [comment]
same prob

**Comment by maxgalbu** [comment]
Due to the latest changes in encryption of NBA streams, the old seasons are not playable using kodi current version

Please correct me if I'm wrong @mkorganashvili
