### ISSUE TITLE
Nothing works anymore - rather live neither archive

### ISSUE THREAD

**Issue by elschmidtorado** [maxgalbu/xbmc.plugin.video.nba#77]
Till yesterday i watches games, but today nothing is workin, wtf has changed ????  Can you help ????

**Comment by maliapac** [comment]
We can only hope that kodi will be updated to accept the new stream format. If that happens, hopefully the addon will be updated too.

**Comment by elschmidtorado** [comment]
what kind of type are the new stream format that it isnt workin in kodi??? 
I installed the pre alpha of Kodi Leia just for checking but of course the nba add on isnt workin.... :-(

**Comment by mkorganashvili** [comment]
mpd (mpeg dash)

**Comment by mkorganashvili** [comment]
There are some ways to play mpd, just figuring it out

**Comment by ivankokan** [comment]
It should be possible to do it (https://github.com/peak3d/inputstream.adaptive), and I'm working on this - no guarantee I will make it. Please, don't comment things are not working anymore as we are all aware of it, and know what has changed.

**Comment by nickomaru** [comment]
there is support SAMPLE-AES?

`[hls,applehttp @ 0000000002702c60] Failed to open segment of playlist 0
[hls,applehttp @ 0000000002702c60] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 0000000002702c60] Failed to open segment of playlist 0
[hls,applehttp @ 0000000002702c60] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 0000000002702c60] Failed to open segment of playlist 0
[hls,applehttp @ 0000000002702c60] Error when loading first segment 'https://neunlds348.akamaized.net/nlds_vod/nba/vod/2018/03/25/nlncp/21701094/d59673e0-4182-3de2-159e-4192d05c25c8/v1
stream/2_21701094_cle_bkn_2017_a_whole_1_6000_000000.ts'`

**Comment by maxgalbu** [comment]
Should be ok thanks to this pull request (https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/78) - at least for archive games. Please download zip from Releases here on github
