### ISSUE TITLE
Many full archive games not working

### ISSUE THREAD

**Issue by whotookmynick** [maxgalbu/xbmc.plugin.video.nba#8]
I have tried setting many different bit rates in the plugin settings and nothing.
Example game: 2015-12-18 Pistons vs Bulls (Full game, home feed)
I get a "Failed to get video Url...." error and then it switches to "Video not found"
I tried switching all the bitrates in the plugin settings and still nothing.

**Comment by maxgalbu** [comment]
It works for me. What else doesn't work - condensed, nba tv live, live games (excluding videos because they work without being logged in)? Does playing from watch.nba.com work?

**Comment by chovy** [comment]
You should install Kodi Log Uploader and send us the link.

**Comment by maxgalbu** [comment]
Closing now, please reopen if the issue reappears..
