### ISSUE TITLE
Can't install the new master file in kodi

### ISSUE THREAD

**Issue by angus1225** [maxgalbu/xbmc.plugin.video.nba#82]
I don't know if is only me... but I can't install the new file. 
It keeps saying:

19:19:49 T:1883102384   ERROR: Previous line repeats 56 times.
19:19:49 T:1883102384   ERROR: CAddonInstallJob[plugin.video.nba]: The dependency on script.module.inputstreamhelper version 0.3.3 could not be satisfied.
19:19:49 T:1865047520   ERROR: EXCEPTION: XBMC is not playing any file

Do you know what can be wrong?
Still can view any match or stream...

**Comment by laconical77** [comment]
I downloaded the latest master and manually unzipped it into /storage/.kodi/addons/plugin.video.nba overwriting the existing files. Then I downloaded inputstreamhelper from [https://github.com/emilsvennesson/script.module.inputstreamhelper](url) and installed it via the normal 'install addon from zip file' option. It's now working for me.

**Comment by maxgalbu** [comment]
Which Kodi version and system (raspberry, desktop, arm or not)?

**Comment by angus1225** [comment]
Its a smart tv amlogic meson8b
Android 4.4.2 api level 19
Architecture ARMv7 processor rev 1
Render Mali 450 mp
Opengl es 2.0
Kodi 16.4 (spmc)

**Comment by angus1225** [comment]
laconical77 I can't install the script...
It says:
The dependencies on xbmc.python version 2.25.0 couldn't be satisfied ....
Thanks anyway

**Comment by angus1225** [comment]
As far as I know... it's impossible with android 442 :(

**Comment by maxgalbu** [comment]
Apparently, inputstream.adaptive is only available from 17 onwards. https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/19#issuecomment-380223060

With HLS gone, ffmpeg and Kodi < 17 are out of the question.

**Comment by angus1225** [comment]
@maxgalbu and @laconical77 very very thank you for your help!
I think im done with NBA on my room TV. 
This Smart tv will not update the Android versión, and the nba app doesnt work (dont know why) neither...
Kodi and your addon was my solution for years....
Thanks a lot for that!
I will keep searching the way to put kodi 17 in this tv...
I will try the 17.6 for Android box from the link you gave uo there... will see
Thanks again

**Comment by laconical77** [comment]
@angus1225 I'd suggest not bothering with the tv and buy either a raspberry pi (that's what I use) or a mi box. Cheap and easy and rock solid.
