### ISSUE TITLE
Archive - Pre Season Games 2019/2020 not visible

### ISSUE THREAD

**Issue by SeBruno** [maxgalbu/xbmc.plugin.video.nba#96]
Dear @ivankokan and @maxgalbu,
first of all, thank you very much  for your highly appreciated work...... so far 
almost every season was very enjoyable via KODI and the Addon you've made UP and developed.

Since the pre-season is already going.... 
I opened Kodi as usual 
and clicked on 
                     - the NBA league pass addon
                           - Archive
                              - no Games ..... nothing appears....

My mostly used Platform/ System:
PC - Windows 10
Kodi 18.4

Its very possible that i maybe missed some infomations about problems under win 10 ....
If they exist??
Hopefully someone can tell me.....

I really understand, you might have different interests and things to do right now...
rather than looking after this application ....... 
So in my case its not that kind of an "issue" , more a question 
if this problem exists only for me or may be someone else...... ? 
And.... is there probably.... already a known solution - which i dont know?                          

Should i try it with the/ a Linux Platform....... somthing like libreelec ?

Best regards - thumbs up for your work
and shout out to YOU!!!

Bruno 
from Germany

**Comment by cablegoon** [comment]
Was going to start a new thread but saw this - same issue on 18.4 on a Android device with the latest Zip from the Repo

**Comment by ivankokan** [comment]
No issues on Win 10, Kodi 18 for me. Use the latest version from my fork containing some critical fixes (done last season).

More about the future can be found here: https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/92.

**Comment by ivankokan** [comment]
Hm, I just checked again. Archive, both This week and Last week are empty indeed. I had first Houston pre-season game few days ago, playing as expected.

I will take care of this in the following days.

**Comment by SeBruno** [comment]
Thank you very much
and thumbs up to   **@ivankokan** - for the quick **reply**!!!

Thank you as well to **@cablegoon** , for confirming the issue in a different operating-system!

Greetings from Germany
Bruno

**Comment by ivankokan** [comment]
Try with the latest in my fork.

**Comment by SeBruno** [comment]
> Try with the latest in my fork.

Just did it...... and....

**THANK YOU VERY MUCH!!!!!!   :D 
It's a "joy"..... Works fluently-fine-again!!!!** 

Greetings from Germany
Bruno

**Comment by SeBruno** [comment]
For me - the issue is closed - 
So i will close this thread ..... ok everybody?
ok @cablegoon? 
                 -If not, you might open a new thread, but i hope that it's working for you too - again!!

Best regards and 
**shout out to @ivankokan for his quick reaction  and solving this "issue"**

**Comment by ivankokan** [comment]
Done in ae51ea4.
