### ISSUE TITLE
Install Guide -AFTV

### ISSUE THREAD

**Issue by as3474** [maxgalbu/xbmc.plugin.video.nba#97]
Hi Guys, 

Thanks for all of your work on this add-on. I only had it briefly working for a few months at the beginning of last season, or two seasons ago, but really enjoyed the interface and being able to watch through Kodi...its so much better than hooking my computer up to my tv.  

I'm wondering if anyone can put together an install guide based on the latest updates to tell users how to install from scratch. 

I've tried to add/update inputstream.adaptive and helper, I've pulled the version from here to zip and tried to install on Kodi, and have also tried to update/install widevine. Decided at this point that it's too confusing to keep trying things and am hoping it's more straightforward to start from scratch. 

Fire TV Stick 4k, International League Pass. 

I know I need to start with Kodi 18, and not use the Kodi repo version. 

If it's too much effort to throw together a guide, I completely understand, and sorry if this info lives somewhere else. 

Thanks for your help, let me know if there is info I can provide from my side to make this easier.

**Comment by ivankokan** [comment]
Hi. The procedure is pretty simple: download the latest and install it (that will automatically install all dependencies as well). Kodi 18 is mandatory.

When I say "the latest", I mean of the latest in my fork (https://github.com/ivankokan/xbmc.plugin.video.nba), which is still not merged in here. (Follow this Pull Request: https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/92.)

**Comment by as3474** [comment]
Not sure what was going on with my FireTVBox and Android TV, but Its working now on my new 4k FireTV Stick.  

Thanks so much for your help.

**Comment by elschmidtorado** [comment]
Hi Ivan,

i installed for testing on my win 10 pro Laptop the latest Kodi Leia 18.4, and installed your latest master nba addon. I installed widewine through another addon because windewine install request was not coming from the nba addon itself !?!?! 
The new links are working but if i want to play any archived game it isnt working. It pops in the right top "Error NBA Addon" Are you logged in" blablabla.  Do i have something forgotten??
Highlights are working. Input Stream Adaptive is on. 

greeting and i am so thankful that you are doing the support for this addon.

**Comment by ivankokan** [comment]
@elschmidtorado Archive should work only for the current season. https://github.com/ivankokan/xbmc.plugin.video.nba/blob/master/Readme.md

**Comment by ivankokan** [comment]
@elschmidtorado Have you tried again?

**Comment by elschmidtorado** [comment]
Hi Ivan,

what should i try again? You said the archives just work on the current season. But since now, there are just Pre-Season games which are not working on Kodi. On my Laptop with Chrome, some games are watchable from the nba.com website relive. 
Of course i can try it again. What about the failing widewine install request from nbaleagepass addon !?!?!? Can i help with any files or anything else?? Logs etc??

**Comment by ivankokan** [comment]
> Hi Ivan,
> 
> what should i try again? You said the archives just work on the current season. But since now, there are just Pre-Season games which are not working on Kodi. On my Laptop with Chrome, some games are watchable from the nba.com website relive.
> Of course i can try it again. What about the failing widewine install request from nbaleagepass addon !?!?!? Can i help with any files or anything else?? Logs etc??

Please go through this checklist (just tested everything on my machine):
- Kodi 18 is mandatory
- the latest version from my fork is installed (https://github.com/ivankokan/xbmc.plugin.video.nba/tree/master)
- you have valid NBA League Pass account
- username (e-mail) and password are provided in add-on Settings
- test e.g. OKC @ DAL 2019-10-14 (Archive)

Dependencies on Widevine (e.g. add-ons inputstreamhelper, inputstream.adaptive) are automatically handled by Kodi. If downloading and installing them failed, try again uninstalling them from your Add-ons. Last resort: https://github.com/emilsvennesson/script.module.inputstreamhelper, https://github.com/peak3d/inputstream.adaptive.

Kind regards, Ivan

**Comment by elschmidtorado** [comment]
> Please go through this checklist (just tested everything on my machine):

Kodi 18 is mandatory
the latest version from my fork is installed (https://github.com/ivankokan/xbmc.plugin.video.nba/tree/master)
you have valid NBA League Pass account
username (e-mail) and password are provided in add-on Settings
test e.g. OKC @ DAL 2019-10-14 (Archive)

Perfect, on my PC its working. Now hopefully i will try it on my CoreElec Kodi Box. Mini M8II Box.

thx so much. I will give you feedback if its working on my kodibox aswell.

**Comment by ivankokan** [comment]
> Perfect, on my PC its working. Now hopefully i will try it on my CoreElec Kodi Box. Mini M8II Box.
> 
> thx so much. I will give you feedback if its working on my kodibox aswell.

Upon successful? testing on other systems, @as3474 please close the issue.

**Comment by elschmidtorado** [comment]
Hi Ivan,
so i installed your lates release on my CoreElec Mini M8II Box and it works. The latest PreSeason Games are working. It took a long while for installing Widewine update boot after reboot it works.

thx a lot

**Comment by ivankokan** [comment]
@as3474, I guess you can close this now?
