### ISSUE TITLE
Wierd error

### ISSUE THREAD

**Issue by Elschnuppero** [maxgalbu/xbmc.plugin.video.nba#98]
Hi there,

first big thx to @ivankokan for taking care of this plugin.

Now i have the following issue:

I made a fresh install of kodi (libreelec leia 18.4) on raspberry pi. When i try to watch a game (e.g. NO-TOR from tonight) i get the error "cannot login: invalid username and password". I triple checked my settings and login and password are right and working in watch.nba.com. 
The error log on the other hands shows a ton of other errors: http://paste.kodi.tv/ufaxaxefup

Thanks in advance

**Comment by ivankokan** [comment]
Can you please enable Debug log (system-wide and add-ons') and upload the log again?

**Comment by Elschnuppero** [comment]
Thank you for your quick response. 
The solution was simple and related to the nba. They locked my password right when i tried to log in from the new kodi device. I didnt notice until i tried to log in on watch.nba.com again. I did the reset and now everything works fine. 

Thanks

**Comment by ivankokan** [comment]
Please close.
