### ISSUE TITLE
NBA TV Live doest not work

### ISSUE THREAD

**Issue by ghost** [maxgalbu/xbmc.plugin.video.nba#99]
Hello @ivankokan , i updatemy kodi 18.4 with your fork : https://github.com/ivankokan/xbmc.plugin.video.nba/tree/master

There is just NBA TV Live doesn't work ?

Newbie don't know where to find the logs ? (i enalbe but nothing happen !)

Thanks for your work.

**Comment by ivankokan** [comment]
> There is just NBA TV Live doesn't work ?

That is true. It has not been working for awhile (years). I am about to handle this very soon.

> Newbie don't know where to find the logs ? (i enalbe but nothing happen !)

In general: https://kodi.wiki/view/Log_file. You do not need to generate logs for non-working NBA TV Live.

**Comment by ghost** [comment]
Great thanks.

**Comment by ivankokan** [comment]
@mehkera You can expect working NBA TV today.

**Comment by ivankokan** [comment]
@mehkera Please use the latest from my fork and enjoy NBA TV. (Only Live for the moment.)

**Comment by ivankokan** [comment]
Done in 52328d7.
